### PR TITLE
Uploads and more

### PR DESCRIPTION
**Pull request by ryanhinkel**
This branch is called uploads because the primary goal was to display upload bars when files were being uploaded. 

In the process, I added a set of controller functions which are called from the views. I also shifted towards  model driven api requests. The vertex model gains the responsibility of keeping the back end in sync and maintaining the state of the synchronization. In doing this, I moved away from the working, but syntactically nutzo request library and adopted caolan's javascript async library. 

Because the code was a bit tangled up when making requests to the server, this refactor touched many parts of the application, such as the save / close buttons on the forms.

The ability to handle different media types has been added. Right now, only mp3 and m4a are accepted and create an "audio" vertex.

Legacy functions have been cleared out and lots of comments have been updated as well. 

And GOD mode has a few more features and is more fun now.

### CODE REVIEW

**Comment by di** [comment]
Looks pretty good to me. Can you push up the changes to `toolbox` as well?

**Comment by ryanhinkel** [comment]
Everything up to date

**Comment by di** [comment]
Yeah, you'll need to merge that, pull the submodule down, and update this PR b/c the hash will change.

**Comment by ryanhinkel** [comment]
I thought we weren't merging our own requests! Looks bad. You should do it!
Then I'll update the pr

**Pull request merged**
